site:
  title: Managed Plugins Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  managed-plugins:ROOT:Home.adoc

content:
  sources:
    - url: ./
      branches: master
      edit_url: false
ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./docs
